# Color Tracking Example

#### To get other flags, just run following commands in your Python terminal

In [ ]:
import cv2
flags = [i for i in dir(cv2) if i.startswith('COLOR_')]
print(flags)

#### Hue range is [0,79], Saturation range is [0,255] and Value range is [0,255])


### Only one color tracking

In [34]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while cap.isOpened()==True:
    #cv2.namedWindow("Aung Thiha",cv2.WINDOW_GUI_NORMAL)
    ret,frame = cap.read()
    
    hsv = cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
    
    #green
    #low = np.array([[[55,170,130]]])
    #high = np.array([[[140,255,255]]])
    
    #red
    low_red = np.array(([165, 170, 130]))
    high_red = np.array(([255, 255, 255]))
    
    #blue
    low_blue = np.array([70, 170, 130])
    high_blue = np.array([160, 255, 255])
    
    
    mask_blue = cv2.inRange(hsv,low_blue,high_blue)
    mask_red = cv2.inRange(hsv,low_red,high_red)
    
    color_track = cv2.bitwise_and(frame,frame, mask= mask_blue)
    
    cv2.imshow("Aung Thiha",frame)
    cv2.imshow("HSV" , color_track)
    k = cv2.waitKey(1) & 0XFF
    if k ==27:
        break

cap.release()
cv2.destroyAllWindows()

###  Two Colors Tracking

In [35]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while cap.isOpened()==True:
    #cv2.namedWindow("Aung Thiha",cv2.WINDOW_GUI_NORMAL)
    ret,frame = cap.read()
    
    hsv = cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
    
    #green
    #low = np.array([[[55,170,130]]])
    #high = np.array([[[140,255,255]]])
    
    #red
    low_red = np.array(([165, 170, 130]))
    high_red = np.array(([255, 255, 255]))
    
    #blue
    low_blue = np.array([70, 170, 130])
    high_blue = np.array([160, 255, 255])
    
    mask_blue = cv2.inRange(hsv,low_blue,high_blue)
    mask_red = cv2.inRange(hsv,low_red,high_red)
    
    color_track_blue = cv2.bitwise_and(frame,frame, mask= mask_blue)
    color_track_red = cv2.bitwise_and(frame,frame, mask= mask_red)
    
    red_blue_tracking = color_track_blue + color_track_red
    
    cv2.imshow("Aung Thiha",frame)
    cv2.imshow("HSV" , red_blue_tracking)
    k = cv2.waitKey(1) & 0XFF
    if k ==27:
        break

cap.release()
cv2.destroyAllWindows()

## How to find HSV values to track?

### Green color for HSV

In [15]:
import numpy as np

green = np.uint8([[[0,255,0 ]]])
hsv_green = cv2.cvtColor(green,cv2.COLOR_BGR2HSV)
print(hsv_green)

[[[ 60 255 255]]]


### Red color for HSV

In [7]:
import numpy as np

red = np.uint8([[[0,0,255]]])
hsv_red = cv2.cvtColor(red,cv2.COLOR_BGR2HSV)
print(hsv_red)

[[[  0 255 255]]]


### Blue color for HSV

In [11]:
import numpy as np

blue = np.uint8([[[255,0,0]]])
hsv_blue = cv2.cvtColor(blue,cv2.COLOR_BGR2HSV)
print(hsv_blue)

[[[120 255 255]]]
